//
//  File.swift
//  
//
//  Created by Andrei Mirica on 01.03.2023.
//

import Foundation

struct Helper {
    var carList: [Car] = []
    
    init() {
        addCars()
    }
    
    mutating func addCars() {
        carList = [
            Car(manufacturer: "Dacia", model: "Logan"),
            Car(manufacturer: "Dacia", model: "Sandero"),
            Car(manufacturer: "Dacia", model: "Duster"),
            Car(manufacturer: "Dacia", model: "Lodgy"),
            Car(manufacturer: "Dacia", model: "Dokker"),
            Car(manufacturer: "Dacia", model: "Nova"),
            Car(manufacturer: "Dacia", model: "1300"),
            Car(manufacturer: "Dacia", model: "Solenza"),
            Car(manufacturer: "Dacia", model: "Supernova"),
            Car(manufacturer: "Dacia", model: "1304"),
            Car(manufacturer: "Dacia", model: "1310"),
            Car(manufacturer: "Dacia", model: "1410"),
            Car(manufacturer: "Dacia", model: "Solenza"),
            Car(manufacturer: "Dacia", model: "Logan MCV"),
            Car(manufacturer: "Dacia", model: "1302"),
            Car(manufacturer: "Dacia", model: "1325 Liberta"),
            // BMW
            Car(manufacturer: "BMW", model: "3 Series"),
            Car(manufacturer: "BMW", model: "5 Series"),
            Car(manufacturer: "BMW", model: "X5"),
            Car(manufacturer: "BMW", model: "7 Series"),
            Car(manufacturer: "BMW", model: "X3"),
            Car(manufacturer: "BMW", model: "1 Series"),
            Car(manufacturer: "BMW", model: "4 Series"),
            Car(manufacturer: "BMW", model: "X1"),
            Car(manufacturer: "BMW", model: "2 Series"),
            Car(manufacturer: "BMW", model: "6 Series"),
            Car(manufacturer: "BMW", model: "Z4"),
            Car(manufacturer: "BMW", model: "8 Series"),
            Car(manufacturer: "BMW", model: "i3"),
            Car(manufacturer: "BMW", model: "i8"),
            Car(manufacturer: "BMW", model: "M2"),
            Car(manufacturer: "BMW", model: "M4"),
            Car(manufacturer: "BMW", model: "M5"),
            Car(manufacturer: "BMW", model: "M6"),
            // VW
            Car(manufacturer: "Volkswagen", model: "Golf"),
            Car(manufacturer: "Volkswagen", model: "Passat"),
            Car(manufacturer: "Volkswagen", model: "Polo"),
            Car(manufacturer: "Volkswagen", model: "Tiguan"),
            Car(manufacturer: "Volkswagen", model: "Touran"),
            Car(manufacturer: "Volkswagen", model: "Arteon"),
            Car(manufacturer: "Volkswagen", model: "Sharan"),
            Car(manufacturer: "Volkswagen", model: "Up!"),
            Car(manufacturer: "Volkswagen", model: "T-Roc"),
            Car(manufacturer: "Volkswagen", model: "Caddy"),
            Car(manufacturer: "Volkswagen", model: "Transporter"),
            Car(manufacturer: "Volkswagen", model: "California"),
            Car(manufacturer: "Volkswagen", model: "Scirocco"),
            Car(manufacturer: "Volkswagen", model: "Jetta"),
            Car(manufacturer: "Volkswagen", model: "Passat CC"),
            Car(manufacturer: "Volkswagen", model: "Bora"),
            Car(manufacturer: "Volkswagen", model: "Beetle"),
            Car(manufacturer: "Volkswagen", model: "Karmann Ghia"),
            // Audi
            Car(manufacturer: "Audi", model: "A4"),
            Car(manufacturer: "Audi", model: "A6"),
            Car(manufacturer: "Audi", model: "Q5"),
            Car(manufacturer: "Audi", model: "A3"),
            Car(manufacturer: "Audi", model: "A5"),
            Car(manufacturer: "Audi", model: "Q3"),
            Car(manufacturer: "Audi", model: "A1"),
            Car(manufacturer: "Audi", model: "A7"),
            Car(manufacturer: "Audi", model: "Q2"),
            Car(manufacturer: "Audi", model: "TT"),
            Car(manufacturer: "Audi", model: "Q7"),
            Car(manufacturer: "Audi", model: "R8"),
            Car(manufacturer: "Audi", model: "A8"),
            Car(manufacturer: "Audi", model: "S3"),
            Car(manufacturer: "Audi", model: "S5"),
            Car(manufacturer: "Audi", model: "S7"),
            Car(manufacturer: "Audi", model: "SQ5"),
            Car(manufacturer: "Audi", model: "RS3"),
            // Ford
            Car(manufacturer: "Ford", model: "Focus"),
            Car(manufacturer: "Ford", model: "Fiesta"),
            Car(manufacturer: "Ford", model: "Kuga"),
            Car(manufacturer: "Ford", model: "EcoSport"),
            Car(manufacturer: "Ford", model: "Mondeo"),
            Car(manufacturer: "Ford", model: "Mustang"),
            Car(manufacturer: "Ford", model: "Galaxy"),
            Car(manufacturer: "Ford", model: "S-Max"),
            Car(manufacturer: "Ford", model: "Edge"),
            Car(manufacturer: "Ford", model: "Tourneo Custom"),
            Car(manufacturer: "Ford", model: "Transit Custom"),
            Car(manufacturer: "Ford", model: "Transit"),
            Car(manufacturer: "Ford", model: "C-Max"),
            Car(manufacturer: "Ford", model: "Grand C-Max"),
            Car(manufacturer: "Ford", model: "Ka+"),
            Car(manufacturer: "Ford", model: "B-Max"),
            Car(manufacturer: "Ford", model: "S-Max Vignale"),
            Car(manufacturer: "Ford", model: "Galaxy Vignale"),
            // Kia
            Car(manufacturer: "Kia", model: "Sportage"),
            Car(manufacturer: "Kia", model: "Ceed"),
            Car(manufacturer: "Kia", model: "Sorento"),
            Car(manufacturer: "Kia", model: "Picanto"),
            Car(manufacturer: "Kia", model: "Niro"),
            Car(manufacturer: "Kia", model: "Stinger"),
            Car(manufacturer: "Kia", model: "Optima"),
            Car(manufacturer: "Kia", model: "Rio"),
            Car(manufacturer: "Kia", model: "Xceed"),
            Car(manufacturer: "Kia", model: "Pro Creed"),
            Car(manufacturer: "Kia", model: "Venga"),
            Car(manufacturer: "Kia", model: "Cerato"),
            Car(manufacturer: "Kia", model: "Carens"),
            Car(manufacturer: "Kia", model: "Magentis"),
            Car(manufacturer: "Kia", model: "Opirus"),
            Car(manufacturer: "Kia", model: "Soul"),
            Car(manufacturer: "Kia", model: "Mohave"),
            Car(manufacturer: "Kia", model: "Quoris"),
            Car(manufacturer: "Kia", model: "K900"),
            // Hyundai
            Car(manufacturer: "Hyundai", model: "Tucson"),
            Car(manufacturer: "Hyundai", model: "i30"),
            Car(manufacturer: "Hyundai", model: "Santa Fe"),
            Car(manufacturer: "Hyundai", model: "Kona"),
            Car(manufacturer: "Hyundai", model: "i20"),
            Car(manufacturer: "Hyundai", model: "ix35"),
            Car(manufacturer: "Hyundai", model: "Accent"),
            Car(manufacturer: "Hyundai", model: "Elantra"),
            Car(manufacturer: "Hyundai", model: "Sonata"),
            Car(manufacturer: "Hyundai", model: "i40"),
            Car(manufacturer: "Hyundai", model: "Veloster"),
            Car(manufacturer: "Hyundai", model: "Genesis"),
            Car(manufacturer: "Hyundai", model: "Azera"),
            Car(manufacturer: "Hyundai", model: "Grandeur"),
            Car(manufacturer: "Hyundai", model: "Equus"),
            Car(manufacturer: "Hyundai", model: "i10"),
            Car(manufacturer: "Hyundai", model: "Santamo"),
            Car(manufacturer: "Hyundai", model: "Atos"),
            Car(manufacturer: "Hyundai", model: "Getz"),
            Car(manufacturer: "Hyundai", model: "Matrix"),
            // Tesla
            Car(manufacturer: "Tesla", model: "Model S"),
            Car(manufacturer: "Tesla", model: "Model 3"),
            Car(manufacturer: "Tesla", model: "Model X"),
            Car(manufacturer: "Tesla", model: "Model Y"),
            Car(manufacturer: "Tesla", model: "Roadster"),
            Car(manufacturer: "Tesla", model: "Cybertruck"),
            Car(manufacturer: "Tesla", model: "Semi"),
            
            // Renault
            Car(manufacturer: "Renault", model: "Clio"),
            Car(manufacturer: "Renault", model: "Megane"),
            Car(manufacturer: "Renault", model: "Captur"),
            Car(manufacturer: "Renault", model: "Scenic"),
            Car(manufacturer: "Renault", model: "Talisman"),
            Car(manufacturer: "Renault", model: "Zoe"),
            Car(manufacturer: "Renault", model: "Kadjar"),
            Car(manufacturer: "Renault", model: "Koleos"),
            Car(manufacturer: "Renault", model: "Twingo"),
            Car(manufacturer: "Renault", model: "Fluence"),
            Car(manufacturer: "Renault", model: "Laguna"),
            Car(manufacturer: "Renault", model: "Espace"),
            Car(manufacturer: "Renault", model: "Vel Satis"),
            Car(manufacturer: "Renault", model: "Avantime"),
            Car(manufacturer: "Renault", model: "Modus"),
            Car(manufacturer: "Renault", model: "Wind"),
            Car(manufacturer: "Renault", model: "Fuego"),
            Car(manufacturer: "Renault", model: "Alpine"),
            Car(manufacturer: "Renault", model: "5"),
            Car(manufacturer: "Renault", model: "19"),
            Car(manufacturer: "Renault", model: "21"),
            // Nissan
            Car(manufacturer: "Nissan", model: "Qashqai"),
            Car(manufacturer: "Nissan", model: "Juke"),
            Car(manufacturer: "Nissan", model: "X-Trail"),
            Car(manufacturer: "Nissan", model: "Micra"),
            Car(manufacturer: "Nissan", model: "Leaf"),
            Car(manufacturer: "Nissan", model: "Pathfinder"),
            Car(manufacturer: "Nissan", model: "Murano"),
            Car(manufacturer: "Nissan", model: "Navara"),
            Car(manufacturer: "Nissan", model: "Patrol"),
            Car(manufacturer: "Nissan", model: "Terrano"),
            Car(manufacturer: "Nissan", model: "Primera"),
            Car(manufacturer: "Nissan", model: "Maxima"),
            Car(manufacturer: "Nissan", model: "350Z"),
            Car(manufacturer: "Nissan", model: "370Z"),
            Car(manufacturer: "Nissan", model: "Skyline"),
            Car(manufacturer: "Nissan", model: "Silvia"),
            Car(manufacturer: "Nissan", model: "GT-R"),
            Car(manufacturer: "Nissan", model: "Almera"),
            Car(manufacturer: "Nissan", model: "Sunny"),
            Car(manufacturer: "Nissan", model: "Note"),
            // Mercedes
            Car(manufacturer: "Mercedes", model: "C-Class"),
            Car(manufacturer: "Mercedes", model: "E-Class"),
            Car(manufacturer: "Mercedes", model: "S-Class"),
            Car(manufacturer: "Mercedes", model: "A-Class"),
            Car(manufacturer: "Mercedes", model: "B-Class"),
            Car(manufacturer: "Mercedes", model: "GLA"),
            Car(manufacturer: "Mercedes", model: "GLC"),
            Car(manufacturer: "Mercedes", model: "GLE"),
            Car(manufacturer: "Mercedes", model: "GLS"),
            Car(manufacturer: "Mercedes", model: "G-Class"),
            Car(manufacturer: "Mercedes", model: "CLS-Class"),
            Car(manufacturer: "Mercedes", model: "SL-Class"),
            Car(manufacturer: "Mercedes", model: "AMG GT"),
            Car(manufacturer: "Mercedes", model: "SLK-Class"),
            Car(manufacturer: "Mercedes", model: "SLR McLaren"),
            Car(manufacturer: "Mercedes", model: "Maybach S-Class"),
            Car(manufacturer: "Mercedes", model: "Vito"),
            Car(manufacturer: "Mercedes", model: "Sprinter"),
            Car(manufacturer: "Mercedes", model: "V-Class"),
            // Mazda
            Car(manufacturer: "Mazda", model: "3"),
            Car(manufacturer: "Mazda", model: "6"),
            Car(manufacturer: "Mazda", model: "CX-3"),
            Car(manufacturer: "Mazda", model: "CX-5"),
            Car(manufacturer: "Mazda", model: "CX-7"),
            Car(manufacturer: "Mazda", model: "CX-9"),
            Car(manufacturer: "Mazda", model: "MX-5"),
            Car(manufacturer: "Mazda", model: "RX-8"),
            Car(manufacturer: "Mazda", model: "626"),
            Car(manufacturer: "Mazda", model: "323"),
            Car(manufacturer: "Mazda", model: "121"),
            Car(manufacturer: "Mazda", model: "929"),
            Car(manufacturer: "Mazda", model: "RX-7"),
            Car(manufacturer: "Mazda", model: "RX-3"),
            Car(manufacturer: "Mazda", model: "CX-30"),
            Car(manufacturer: "Mazda", model: "MPV"),
            Car(manufacturer: "Mazda", model: "Bongo"),
            // Mitsubishi
            Car(manufacturer: "Mitsubishi", model: "ASX"),
            Car(manufacturer: "Mitsubishi", model: "Outlander"),
            Car(manufacturer: "Mitsubishi", model: "L200"),
            Car(manufacturer: "Mitsubishi", model: "Pajero"),
            Car(manufacturer: "Mitsubishi", model: "Eclipse Cross"),
            Car(manufacturer: "Mitsubishi", model: "Mirage"),
            Car(manufacturer: "Mitsubishi", model: "Colt"),
            Car(manufacturer: "Mitsubishi", model: "Galant"),
            Car(manufacturer: "Mitsubishi", model: "Carisma"),
            Car(manufacturer: "Mitsubishi", model: "Lancer"),
            Car(manufacturer: "Mitsubishi", model: "Space Star"),
            Car(manufacturer: "Mitsubishi", model: "3000GT"),
            Car(manufacturer: "Mitsubishi", model: "Evo"),
            Car(manufacturer: "Mitsubishi", model: "Starion"),
            Car(manufacturer: "Mitsubishi", model: "Sapporo"),
            Car(manufacturer: "Mitsubishi", model: "Challenger"),
            Car(manufacturer: "Mitsubishi", model: "Grandis"),
            Car(manufacturer: "Mitsubishi", model: "Proudia"),
            // Ferrari
            Car(manufacturer: "Ferrari", model: "458 Italia"),
            Car(manufacturer: "Ferrari", model: "488 GTB"),
            Car(manufacturer: "Ferrari", model: "F8 Tributo"),
            Car(manufacturer: "Ferrari", model: "812 Superfast"),
            Car(manufacturer: "Ferrari", model: "GTC4Lusso"),
            Car(manufacturer: "Ferrari", model: "Portofino"),
            Car(manufacturer: "Ferrari", model: "SF90 Stradale"),
            Car(manufacturer: "Ferrari", model: "Enzo"),
            Car(manufacturer: "Ferrari", model: "LaFerrari"),
            Car(manufacturer: "Ferrari", model: "F40"),
            Car(manufacturer: "Ferrari", model: "F50"),
            Car(manufacturer: "Ferrari", model: "288 GTO"),
            Car(manufacturer: "Ferrari", model: "Testarossa"),
            Car(manufacturer: "Ferrari", model: "Dino"),
            Car(manufacturer: "Ferrari", model: "458 Speciale"),
            Car(manufacturer: "Ferrari", model: "California"),
            Car(manufacturer: "Ferrari", model: "599 GTB Fiorano"),
            Car(manufacturer: "Ferrari", model: "456 GT"),
            // McLaren
            Car(manufacturer: "McLaren", model: "570S"),
            Car(manufacturer: "McLaren", model: "600LT"),
            Car(manufacturer: "McLaren", model: "720S"),
            Car(manufacturer: "McLaren", model: "Senna"),
            Car(manufacturer: "McLaren", model: "GT"),
            Car(manufacturer: "McLaren", model: "P1"),
            Car(manufacturer: "McLaren", model: "675LT"),
            Car(manufacturer: "McLaren", model: "650S"),
            Car(manufacturer: "McLaren", model: "MP4-12C"),
            Car(manufacturer: "McLaren", model: "F1"),
            Car(manufacturer: "McLaren", model: "Mercedes-Benz SLR McLaren"),
            Car(manufacturer: "McLaren", model: "F1 LM"),
            Car(manufacturer: "McLaren", model: "570GT"),
            Car(manufacturer: "McLaren", model: "620R"),
            Car(manufacturer: "McLaren", model: "765LT"),
            Car(manufacturer: "McLaren", model: "Artura"),
            Car(manufacturer: "McLaren", model: "MP4-12C Spider"),
            Car(manufacturer: "McLaren", model: "540C"),
            // Alfa Romeo
            Car(manufacturer: "Alfa Romeo", model: "Giulia"),
            Car(manufacturer: "Alfa Romeo", model: "Stelvio"),
            Car(manufacturer: "Alfa Romeo", model: "4C"),
            Car(manufacturer: "Alfa Romeo", model: "8C"),
            Car(manufacturer: "Alfa Romeo", model: "Giulietta"),
            Car(manufacturer: "Alfa Romeo", model: "156"),
            Car(manufacturer: "Alfa Romeo", model: "147"),
            Car(manufacturer: "Alfa Romeo", model: "159"),
            Car(manufacturer: "Alfa Romeo", model: "166"),
            Car(manufacturer: "Alfa Romeo", model: "GT"),
            Car(manufacturer: "Alfa Romeo", model: "Spider"),
            Car(manufacturer: "Alfa Romeo", model: "Brera"),
            Car(manufacturer: "Alfa Romeo", model: "GTV"),
            Car(manufacturer: "Alfa Romeo", model: "SZ"),
            Car(manufacturer: "Alfa Romeo", model: "RZ"),
            Car(manufacturer: "Alfa Romeo", model: "33"),
            Car(manufacturer: "Alfa Romeo", model: "75"),
            Car(manufacturer: "Alfa Romeo", model: "164"),
            // Chevrolet
            Car(manufacturer: "Chevrolet", model: "Camaro"),
            Car(manufacturer: "Chevrolet", model: "Corvette"),
            Car(manufacturer: "Chevrolet", model: "Silverado"),
            Car(manufacturer: "Chevrolet", model: "Tahoe"),
            Car(manufacturer: "Chevrolet", model: "Malibu"),
            Car(manufacturer: "Chevrolet", model: "Impala"),
            Car(manufacturer: "Chevrolet", model: "Suburban"),
            Car(manufacturer: "Chevrolet", model: "Equinox"),
            Car(manufacturer: "Chevrolet", model: "Trailblazer"),
            Car(manufacturer: "Chevrolet", model: "Blazer"),
            Car(manufacturer: "Chevrolet", model: "Avalanche"),
            Car(manufacturer: "Chevrolet", model: "Cruze"),
            Car(manufacturer: "Chevrolet", model: "Volt"),
            Car(manufacturer: "Chevrolet", model: "Bolt"),
            Car(manufacturer: "Chevrolet", model: "Spark"),
            Car(manufacturer: "Chevrolet", model: "Trax"),
            Car(manufacturer: "Chevrolet", model: "Sonic"),
            Car(manufacturer: "Chevrolet", model: "HHR"),
            Car(manufacturer: "Chevrolet", model: "Express"),
            Car(manufacturer: "Chevrolet", model: "Colorado"),
            Car(manufacturer: "Chevrolet", model: "SSR"),
            Car(manufacturer: "Chevrolet", model: "Caprice"),
            Car(manufacturer: "Chevrolet", model: "Chevelle"),
            Car(manufacturer: "Chevrolet", model: "Nova"),
            
            Car(manufacturer: "Honda", model: "Civic"),
            Car(manufacturer: "Honda", model: "Accord"),
            Car(manufacturer: "Honda", model: "CR-V"),
            Car(manufacturer: "Honda", model: "HR-V"),
            Car(manufacturer: "Honda", model: "Jazz"),
            Car(manufacturer: "Honda", model: "Insight"),
            Car(manufacturer: "Honda", model: "Integra"),
            Car(manufacturer: "Honda", model: "Legend"),
            Car(manufacturer: "Honda", model: "Prelude"),
            Car(manufacturer: "Honda", model: "S2000"),
            Car(manufacturer: "Honda", model: "Stream"),
            Car(manufacturer: "Honda", model: "FR-V"),
            Car(manufacturer: "Honda", model: "CR-Z"),
            Car(manufacturer: "Honda", model: "NSX"),
            Car(manufacturer: "Honda", model: "City"),
            
            Car(manufacturer: "Toyota", model: "Corolla"),
            Car(manufacturer: "Toyota", model: "Yaris"),
            Car(manufacturer: "Toyota", model: "Auris"),
            Car(manufacturer: "Toyota", model: "Avensis"),
            Car(manufacturer: "Toyota", model: "Prius"),
            Car(manufacturer: "Toyota", model: "Rav4"),
            Car(manufacturer: "Toyota", model: "Land Cruiser"),
            Car(manufacturer: "Toyota", model: "Camry"),
            Car(manufacturer: "Toyota", model: "Verso"),
            Car(manufacturer: "Toyota", model: "C-HR"),
            Car(manufacturer: "Toyota", model: "Highlander"),
            Car(manufacturer: "Toyota", model: "Supra"),
            Car(manufacturer: "Toyota", model: "GT86"),
            Car(manufacturer: "Toyota", model: "Celica"),
            Car(manufacturer: "Toyota", model: "MR2"),
            
            Car(manufacturer: "Opel", model: "Astra"),
            Car(manufacturer: "Opel", model: "Corsa"),
            Car(manufacturer: "Opel", model: "Insignia"),
            Car(manufacturer: "Opel", model: "Zafira"),
            Car(manufacturer: "Opel", model: "Vectra"),
            Car(manufacturer: "Opel", model: "Meriva"),
            Car(manufacturer: "Opel", model: "Mokka"),
            Car(manufacturer: "Opel", model: "Adam"),
            Car(manufacturer: "Opel", model: "Antara"),
            Car(manufacturer: "Opel", model: "Agila"),
            Car(manufacturer: "Opel", model: "Tigra"),
            Car(manufacturer: "Opel", model: "Karl"),
            Car(manufacturer: "Opel", model: "Ampera"),
            Car(manufacturer: "Opel", model: "GT"),
            Car(manufacturer: "Opel", model: "Calibra"),
            
            Car(manufacturer: "Skoda", model: "Octavia"),
            Car(manufacturer: "Skoda", model: "Fabia"),
            Car(manufacturer: "Skoda", model: "Superb"),
            Car(manufacturer: "Skoda", model: "Yeti"),
            Car(manufacturer: "Skoda", model: "Rapid"),
            Car(manufacturer: "Skoda", model: "Kodiaq"),
            Car(manufacturer: "Skoda", model: "Citigo"),
            Car(manufacturer: "Skoda", model: "Scala"),
            Car(manufacturer: "Skoda", model: "Karoq"),
            Car(manufacturer: "Skoda", model: "Roomster"),
            Car(manufacturer: "Skoda", model: "Felicia"),
            Car(manufacturer: "Skoda", model: "Favorit"),
            Car(manufacturer: "Skoda", model: "Forman"),
            Car(manufacturer: "Skoda", model: "120"),
            Car(manufacturer: "Skoda", model: "105"),
            
            Car(manufacturer: "Peugeot", model: "206"),
            Car(manufacturer: "Peugeot", model: "307"),
            Car(manufacturer: "Peugeot", model: "308"),
            Car(manufacturer: "Peugeot", model: "407"),
            Car(manufacturer: "Peugeot", model: "Partner"),
            Car(manufacturer: "Peugeot", model: "206+"),
            Car(manufacturer: "Peugeot", model: "3008"),
            Car(manufacturer: "Peugeot", model: "208"),
            Car(manufacturer: "Peugeot", model: "508"),
            Car(manufacturer: "Peugeot", model: "207"),
            Car(manufacturer: "Peugeot", model: "106"),
            Car(manufacturer: "Peugeot", model: "406"),
            Car(manufacturer: "Peugeot", model: "206 CC"),
            Car(manufacturer: "Peugeot", model: "4007"),
            Car(manufacturer: "Peugeot", model: "205"),
            
            Car(manufacturer: "Porsche", model: "Cayenne"),
            Car(manufacturer: "Porsche", model: "Panamera"),
            Car(manufacturer: "Porsche", model: "911"),
            Car(manufacturer: "Porsche", model: "Macan"),
            Car(manufacturer: "Porsche", model: "Boxster"),
            Car(manufacturer: "Porsche", model: "Cayman"),
            Car(manufacturer: "Porsche", model: "944"),
            Car(manufacturer: "Porsche", model: "928"),
            Car(manufacturer: "Porsche", model: "968"),
            Car(manufacturer: "Porsche", model: "718"),
            Car(manufacturer: "Porsche", model: "924"),
            Car(manufacturer: "Porsche", model: "914"),
            Car(manufacturer: "Porsche", model: "356"),
            Car(manufacturer: "Porsche", model: "959"),
            Car(manufacturer: "Porsche", model: "550"),
            
            Car(manufacturer: "Fiat", model: "Punto"),
            Car(manufacturer: "Fiat", model: "Bravo"),
            Car(manufacturer: "Fiat", model: "Doblo"),
            Car(manufacturer: "Fiat", model: "500"),
            Car(manufacturer: "Fiat", model: "Tipo"),
            Car(manufacturer: "Fiat", model: "Stilo"),
            Car(manufacturer: "Fiat", model: "Cinquecento"),
            Car(manufacturer: "Fiat", model: "Panda"),
            Car(manufacturer: "Fiat", model: "Grande Punto"),
            Car(manufacturer: "Fiat", model: "Seicento"),
            Car(manufacturer: "Fiat", model: "Multipla"),
            Car(manufacturer: "Fiat", model: "Barchetta"),
            Car(manufacturer: "Fiat", model: "124 Spider"),
            Car(manufacturer: "Fiat", model: "124"),
            Car(manufacturer: "Fiat", model: "Coupe")
        ]
        
    }
}
